export const MOCK_MARKETS = [
  {
    id: '1',
    category: 'sports',
    eventSubtitle: 'ATP Challenger Brisbane',
    title: 'Bouzige vs Schoolkate',
    eventImage: 'https://picsum.photos/id/10/112/112',
    outcomes: [
      { label: 'Tristan Schoolkate', pct: 99, aiProb: 95 },
      { label: 'Moerani Bouzige', pct: 1, aiProb: 5 },
    ],
    volume: '$1,222,152',
    isNew: false,
    priceChange: null,
    aiAnalysis: '近期战绩与赔率均偏向 Schoolkate，AI 判断其胜率较高，建议关注盘口变化。',
  },
  {
    id: '2',
    category: 'sports',
    eventSubtitle: 'ATP Challenger Brisbane',
    title: 'Shimizu vs Tokuda',
    eventImage: 'https://picsum.photos/id/11/112/112',
    outcomes: [
      { label: 'Yuta Shimizu', pct: 70, aiProb: 68 },
      { label: 'Renta Tokuda', pct: 31, aiProb: 32 },
    ],
    volume: '$579,799',
    isNew: false,
    priceChange: null,
    aiAnalysis: '双方实力接近，市场与 AI 概率基本一致，波动可能来自临场状态。',
  },
  {
    id: '3',
    category: 'politics',
    eventSubtitle: 'Politics',
    title: 'Margin of victory in the 1st round of the Texas Senate race?',
    eventImage: 'https://picsum.photos/id/20/112/112',
    outcomes: [
      { label: 'Talarico, 0-3%', pct: 3, aiProb: 4 },
      { label: 'Allred, 3-6%', pct: 12, aiProb: 18 },
      { label: 'Allred, 6-9%', pct: 28, aiProb: 35 },
    ],
    volume: '$3,241',
    isNew: false,
    priceChange: null,
    aiAnalysis: '民调显示 Allred 领先，AI 综合历史选区数据认为 6–9% 区间概率被低估。',
  },
  {
    id: '4',
    category: 'politics',
    eventSubtitle: 'Politics',
    title: 'Who will win the Texas Senate election in 2026?',
    eventImage: 'https://picsum.photos/id/21/112/112',
    outcomes: [
      { label: 'Republican', pct: 52, aiProb: 48 },
      { label: 'Democrat', pct: 45, aiProb: 50 },
      { label: 'Other', pct: 3, aiProb: 2 },
    ],
    volume: '$38,981',
    isNew: true,
    priceChange: null,
    aiAnalysis: '两党支持率接近，AI 认为民主党在摇摆选民中略占优，但不确定性仍高。',
  },
  {
    id: '5',
    category: 'politics',
    eventSubtitle: 'Politics',
    title: 'Will Trump win the 2026 presidential election?',
    eventImage: 'https://picsum.photos/id/22/112/112',
    outcomes: [
      { label: 'Yes', pct: 48, aiProb: 45 },
      { label: 'No', pct: 52, aiProb: 55 },
    ],
    volume: '$125,420',
    isNew: false,
    priceChange: { text: 'No offers $100 → $103' },
    aiAnalysis: '当前民调与事件模型下，AI 略偏向 No，建议关注中期选举与政策议题走向。',
  },
  {
    id: '6',
    category: 'politics',
    eventSubtitle: 'Politics',
    title: 'Which party will control the House after 2026?',
    eventImage: 'https://picsum.photos/id/23/112/112',
    outcomes: [
      { label: 'Republican', pct: 44, aiProb: 42 },
      { label: 'Democrat', pct: 51, aiProb: 52 },
      { label: 'Tie', pct: 5, aiProb: 6 },
    ],
    volume: '$67,200',
    isNew: false,
    priceChange: null,
    aiAnalysis: '席位数模型显示民主党小幅领先，Tie 概率被市场略低估，可关注关键选区。',
  },
  {
    id: '7',
    category: 'culture',
    eventSubtitle: 'Culture',
    title: 'Who will attend The 68th Grammy Awards?',
    eventImage: 'https://picsum.photos/id/30/112/112',
    outcomes: [
      { label: 'Benny Blanco', pct: 3, aiProb: 5 },
      { label: 'Jennifer Lopez', pct: 1, aiProb: 2 },
    ],
    volume: '$38,981',
    isNew: false,
    priceChange: null,
    aiAnalysis: '娱乐事件热度高，AI 结合出席历史与档期给出概率。',
  },
  {
    id: '8',
    category: 'crypto',
    eventSubtitle: 'Crypto',
    title: 'Will Bitcoin reach $100k by end of 2025?',
    eventImage: 'https://picsum.photos/id/31/112/112',
    outcomes: [
      { label: 'Yes', pct: 55, aiProb: 52 },
      { label: 'No', pct: 45, aiProb: 48 },
    ],
    volume: '$256,000',
    isNew: false,
    priceChange: null,
    aiAnalysis: '市场与 AI 均略偏多，需关注宏观与监管动态。',
  },
]
